sudo: true
addons:
  apt:
     packages:
      - openssl
    
before_install:
- export CLIURL=https://developer.salesforce.com/media/salesforce-cli/sfdx/channels/stable/sfdx-linux-x64.tar.xz
- export SFDX_AUTOUPDATE_DISABLE=false
- export SFDX_USE_GENERIC_UNIX_KEYCHAIN=true
- export SFDX_DOMAIN_RETRY=300
- export SFDX_DISABLE_APP_HUB=true
- export SFDX_LOG_LEVEL=DEBUG
- mkdir ~/sfdx
- wget -qO- ${DX_CLI_URL_CUSTOM-$CLIURL} | tar xJ -C ~/sfdx --strip-components 1
- export PATH=~/sfdx/bin:$PATH
- sfdx --version
- openssl enc -nosalt -aes-256-cbc -d -in assets/server.key.enc -out assets/server.key
  -base64 -K $encrypted_85b47e2f0acb_key -iv $encrypted_85b47e2f0acb_iv
before_script:
- export DEPLOYDIR=src
- export TESTLEVEL=RunLocalTests
- sfdx --version
- sfdx plugins --core
script:
- sfdx auth:jwt:grant --instanceurl https://test.salesforce.com  --clientid $CONSUMERKEY
  --jwtkeyfile assets/server.key --username $USERNAME --setalias UAT
- sfdx force:mdapi:deploy --wait 10 --deploydir $DEPLOYDIR --targetusername UAT --testlevel
  $TESTLEVEL
